# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PublicationToolCoreIDCCaApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PublicationToolCoreIDCCaApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PublicationToolCoreIDCCaApi }) = "https://publicationtool.jao.eu/core/api"

const _returntypes_publicationtool_idcc_a_allocation_constraint_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_allocation_constraint(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_allocation_constraint_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_allocationConstraint", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Allocation constraints

Core CCR intraday continuous clearing (window A) — Allocation constraints.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_allocation_constraint(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_allocation_constraint(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_congestion_income_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_congestion_income(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_congestion_income_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_congestionIncome", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Congestion income per border

Core CCR intraday continuous clearing (window A) — Congestion income per border.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_congestion_income(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_congestion_income(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_congestion_income(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_congestion_income(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_d2cf_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_d2cf(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_d2cf_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_d2CF", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""D-2 congestion forecast

Core CCR intraday continuous clearing (window A) — D-2 congestion forecast.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_d2cf(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_d2cf(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_d2cf(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_d2cf(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_final_computation_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_final_computation(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_idcc_a_final_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_idcc_a_final_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_final_computation_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_finalComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Final FB domain

Core CCR intraday continuous clearing (window A) — Final FB domain.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_final_computation(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_final_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_final_computation(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_final_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_initial_computation_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_initial_computation(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_idcc_a_initial_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_idcc_a_initial_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_initial_computation_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_initialComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Initial FB domain

Core CCR intraday continuous clearing (window A) — Initial FB domain.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_initial_computation(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_initial_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_initial_computation(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_initial_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_intraday_atc_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_intraday_atc(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_intraday_atc_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_intradayAtc", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Border intraday ATC

Core CCR intraday continuous clearing (window A) — Border intraday ATC.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_intraday_atc(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_intraday_atc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_intraday_atc(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_intraday_atc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_intraday_ntc_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_intraday_ntc(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_intraday_ntc_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_intradayNtc", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Border intraday NTC

Core CCR intraday continuous clearing (window A) — Border intraday NTC.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_intraday_ntc(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_intraday_ntc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_intraday_ntc(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_intraday_ntc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_max_exchanges_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_max_exchanges(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_max_exchanges_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_maxExchanges", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Max bilateral exchanges per border

Core CCR intraday continuous clearing (window A) — Max bilateral exchanges per border.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_max_exchanges(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_max_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_max_exchanges(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_max_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_max_net_positions_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_max_net_positions(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_max_net_positions_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_maxNetPos", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Min/max net positions per zone

Core CCR intraday continuous clearing (window A) — Min/max net positions per zone.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_max_net_positions(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_max_net_positions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_max_net_positions(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_max_net_positions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_net_position_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_net_position(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_net_position_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_netPos", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Net positions per zone

Core CCR intraday continuous clearing (window A) — Net positions per zone.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_net_position(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_net_position(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_net_position(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_net_position(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_prefinal_computation_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_prefinal_computation(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_idcc_a_prefinal_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_idcc_a_prefinal_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_prefinal_computation_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_preFinalComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Pre-final FB domain

Core CCR intraday continuous clearing (window A) — Pre-final FB domain.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_prefinal_computation(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_prefinal_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_prefinal_computation(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_prefinal_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_price_spread_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_price_spread(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_price_spread_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_priceSpread", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Intraday price spreads

Core CCR intraday continuous clearing (window A) — Intraday price spreads.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_price_spread(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_price_spread(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_price_spread(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_price_spread(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_refprog_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_refprog(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_refprog_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_refprog", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Reference programs

Core CCR intraday continuous clearing (window A) — Reference programs.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_refprog(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_refprog(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_refprog(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_refprog(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_scheduled_exchanges_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_scheduled_exchanges(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_scheduled_exchanges_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_scheduledExchanges", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Scheduled exchanges per border

Core CCR intraday continuous clearing (window A) — Scheduled exchanges per border.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_scheduled_exchanges(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_scheduled_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_scheduled_exchanges(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_scheduled_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_idcc_a_validation_reductions_PublicationToolCoreIDCCaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_idcc_a_validation_reductions(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_idcc_a_validation_reductions_PublicationToolCoreIDCCaApi, "/publicationtool/coreID/data/IDCCa_validationReductions", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""TSO validation reductions

Core CCR intraday continuous clearing (window A) — TSO validation reductions.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_idcc_a_validation_reductions(_api::PublicationToolCoreIDCCaApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_validation_reductions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_idcc_a_validation_reductions(_api::PublicationToolCoreIDCCaApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_idcc_a_validation_reductions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export publicationtool_idcc_a_allocation_constraint
export publicationtool_idcc_a_congestion_income
export publicationtool_idcc_a_d2cf
export publicationtool_idcc_a_final_computation
export publicationtool_idcc_a_initial_computation
export publicationtool_idcc_a_intraday_atc
export publicationtool_idcc_a_intraday_ntc
export publicationtool_idcc_a_max_exchanges
export publicationtool_idcc_a_max_net_positions
export publicationtool_idcc_a_net_position
export publicationtool_idcc_a_prefinal_computation
export publicationtool_idcc_a_price_spread
export publicationtool_idcc_a_refprog
export publicationtool_idcc_a_scheduled_exchanges
export publicationtool_idcc_a_validation_reductions
