# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PublicationToolCoreDAApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PublicationToolCoreDAApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PublicationToolCoreDAApi }) = "https://publicationtool.jao.eu/core/api"

const _returntypes_publicationtool_core_da_allocation_constraint_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_allocation_constraint(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_allocation_constraint_PublicationToolCoreDAApi, "/publicationtool/core/data/allocationConstraint", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Allocation constraints (up/down per zone)

External allocation constraints imposed on the flow-based domain (up and down per zone).

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_allocation_constraint(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_allocation_constraint(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_alpha_factor_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_alpha_factor(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_alpha_factor_PublicationToolCoreDAApi, "/publicationtool/core/data/alphaFactor", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Alpha factor per zone

Per-zone alpha factor used in advanced hybrid coupling.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_alpha_factor(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_alpha_factor(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_alpha_factor(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_alpha_factor(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_congestion_income_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_congestion_income(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_congestion_income_PublicationToolCoreDAApi, "/publicationtool/core/data/congestionIncome", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Congestion income per border

Day-ahead congestion rent per border, in EUR.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_congestion_income(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_congestion_income(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_congestion_income(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_congestion_income(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_d2cf_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_d2cf(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_d2cf_PublicationToolCoreDAApi, "/publicationtool/core/data/d2CF", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""D-2 congestion forecast

D-2 congestion forecast (Nordic variant: `cgmForeCast`).

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_d2cf(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_d2cf(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_d2cf(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_d2cf(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_final_computation_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_final_computation(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_core_da_final_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_core_da_final_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_final_computation_PublicationToolCoreDAApi, "/publicationtool/core/data/finalComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Final flow-based domain (CNECs + PTDFs)

Final computation of the Core CCR flow-based domain for the requested market time unit: critical network elements, their contingencies, RAMs, and PTDFs per bidding-zone hub. Paginate via `Skip`/`Take`; use `Filter` to narrow by CNEC, TSO, or presolved state.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_final_computation(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_final_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_final_computation(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_final_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_initial_computation_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_initial_computation(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_core_da_initial_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_core_da_initial_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_initial_computation_PublicationToolCoreDAApi, "/publicationtool/core/data/initialComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Initial flow-based domain

Initial CCM output, before any validation. Same shape as `finalComputation`.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_initial_computation(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_initial_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_initial_computation(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_initial_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_lta_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_lta(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_lta_PublicationToolCoreDAApi, "/publicationtool/core/data/lta", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Long-term allocations

Long-term capacity allocations (yearly/monthly) applicable to the requested window.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_lta(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_lta(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_lta(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_lta(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_max_exchanges_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_max_exchanges(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_max_exchanges_PublicationToolCoreDAApi, "/publicationtool/core/data/maxExchanges", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Maximum bilateral exchanges per border

Per-border max bilateral exchange limits in MW. Columns: `dateTimeUtc` plus `border_<FROM>_<TO>`.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_max_exchanges(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_max_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_max_exchanges(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_max_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_max_net_positions_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_max_net_positions(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_max_net_positions_PublicationToolCoreDAApi, "/publicationtool/core/data/maxNetPos", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Min/max net positions per zone

Per-zone min and max net-position bounds in MW.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_max_net_positions(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_max_net_positions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_max_net_positions(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_max_net_positions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_monitoring_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_monitoring(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_monitoring_PublicationToolCoreDAApi, "/publicationtool/core/system/monitoring", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Process monitoring (deadlines, publication times)

Process monitoring records — `businessDayUtc`, `deadline`, `lastModifiedOn`. Note: served from `/system/` rather than `/data/` on the Publication Tool host.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_monitoring(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_monitoring(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_monitoring(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_monitoring(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_net_position_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_net_position(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_net_position_PublicationToolCoreDAApi, "/publicationtool/core/data/netPos", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Net positions per bidding zone

Net position per Core CCR bidding zone, one row per MTU. Columns: `dateTimeUtc` plus `hub_<ZONE>` (e.g. `hub_DE`, `hub_FR`). Special-case: jao-py renames `DE` → `DE_LU`.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_net_position(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_net_position(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_net_position(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_net_position(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_prefinal_computation_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_prefinal_computation(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_core_da_prefinal_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_core_da_prefinal_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_prefinal_computation_PublicationToolCoreDAApi, "/publicationtool/core/data/preFinalComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Pre-final flow-based domain

Pre-final computation result, prior to TSO validation reductions. Same shape as `finalComputation`.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_prefinal_computation(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_prefinal_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_prefinal_computation(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_prefinal_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_price_spread_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_price_spread(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_price_spread_PublicationToolCoreDAApi, "/publicationtool/core/data/priceSpread", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Day-ahead price spreads per border

Day-ahead price spread per border, derived from SDAC clearing prices.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_price_spread(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_price_spread(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_price_spread(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_price_spread(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_refprog_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_refprog(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_refprog_PublicationToolCoreDAApi, "/publicationtool/core/data/refprog", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Reference programs

Reference programs feeding the flow-based computation.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_refprog(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_refprog(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_refprog(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_refprog(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_scheduled_exchanges_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_scheduled_exchanges(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_scheduled_exchanges_PublicationToolCoreDAApi, "/publicationtool/core/data/scheduledExchanges", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Scheduled exchanges per border

Per-border scheduled exchanges in MW.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_scheduled_exchanges(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_scheduled_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_scheduled_exchanges(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_scheduled_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_shadow_prices_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_shadow_prices(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_shadow_prices_PublicationToolCoreDAApi, "/publicationtool/core/data/shadowPrices", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Active constraints with shadow prices

Critical branch-contingency pairs (CB/CO) that were binding in the market clearing, with their shadow prices.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_shadow_prices(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_shadow_prices(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_shadow_prices(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_shadow_prices(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_spanning_default_fbp_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_spanning_default_fbp(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_spanning_default_fbp_PublicationToolCoreDAApi, "/publicationtool/core/data/spanningDefaultFBP", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Default-FBP status flag

Indicator: did the day fall back to the spanning default flow-based parameters?

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_spanning_default_fbp(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_spanning_default_fbp(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_spanning_default_fbp(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_spanning_default_fbp(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_core_da_validation_reductions_PublicationToolCoreDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_core_da_validation_reductions(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_core_da_validation_reductions_PublicationToolCoreDAApi, "/publicationtool/core/data/validationReductions", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""TSO validation reductions

Per-TSO reductions applied during validation. Note: some rows carry `tso == \"CBCO\"`; jao-py filters those out as malformed.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_core_da_validation_reductions(_api::PublicationToolCoreDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_validation_reductions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_core_da_validation_reductions(_api::PublicationToolCoreDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_core_da_validation_reductions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export publicationtool_core_da_allocation_constraint
export publicationtool_core_da_alpha_factor
export publicationtool_core_da_congestion_income
export publicationtool_core_da_d2cf
export publicationtool_core_da_final_computation
export publicationtool_core_da_initial_computation
export publicationtool_core_da_lta
export publicationtool_core_da_max_exchanges
export publicationtool_core_da_max_net_positions
export publicationtool_core_da_monitoring
export publicationtool_core_da_net_position
export publicationtool_core_da_prefinal_computation
export publicationtool_core_da_price_spread
export publicationtool_core_da_refprog
export publicationtool_core_da_scheduled_exchanges
export publicationtool_core_da_shadow_prices
export publicationtool_core_da_spanning_default_fbp
export publicationtool_core_da_validation_reductions
