# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct OwsmpAuctionsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `OwsmpAuctionsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ OwsmpAuctionsApi }) = "https://publicationtool.jao.eu/core/api"

const _returntypes_owsmp_get_auctions_OwsmpAuctionsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Any},
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_owsmp_get_auctions(_api::OwsmpAuctionsApi, corridor::String, horizon::String, fromdate::Date; todate=nothing, shadow=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_owsmp_get_auctions_OwsmpAuctionsApi, "/owsmp/getauctions", ["OwsmpApiKey", ])
    OpenAPI.Clients.set_param(_ctx.query, "corridor", corridor; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "horizon", horizon; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "fromdate", fromdate; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "todate", todate; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "shadow", shadow; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Auction results

Auction results for a corridor / horizon over a date range (max 31 days). Each entry includes nested `results[]` and `products[]` carrying offered/allocated/requested capacity, ATC, auction price, and bid-gate timestamps. Omit `todate` for the `Yearly` horizon (server ignores it).

Params:
- corridor::String (required)
- horizon::String (required)
- fromdate::Date (required)
- todate::Date
- shadow::Int64

Return: Vector{Any}, OpenAPI.Clients.ApiResponse
"""
function owsmp_get_auctions(_api::OwsmpAuctionsApi, corridor::String, horizon::String, fromdate::Date; todate=nothing, shadow=nothing, _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_auctions(_api, corridor, horizon, fromdate; todate=todate, shadow=shadow, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function owsmp_get_auctions(_api::OwsmpAuctionsApi, response_stream::Channel, corridor::String, horizon::String, fromdate::Date; todate=nothing, shadow=nothing, _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_auctions(_api, corridor, horizon, fromdate; todate=todate, shadow=shadow, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_owsmp_get_bids_OwsmpAuctionsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Any},
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_owsmp_get_bids(_api::OwsmpAuctionsApi, auctionid::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_owsmp_get_bids_OwsmpAuctionsApi, "/owsmp/getbids", ["OwsmpApiKey", ])
    OpenAPI.Clients.set_param(_ctx.query, "auctionid", auctionid; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Bids for a specific auction

Bid-level records for one auction (identified by `auctionid`, e.g. `<CORRIDOR>-M-BASE-------YYMM01-01`).

Params:
- auctionid::String (required)

Return: Vector{Any}, OpenAPI.Clients.ApiResponse
"""
function owsmp_get_bids(_api::OwsmpAuctionsApi, auctionid::String; _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_bids(_api, auctionid; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function owsmp_get_bids(_api::OwsmpAuctionsApi, response_stream::Channel, auctionid::String; _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_bids(_api, auctionid; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_owsmp_get_corridors_OwsmpAuctionsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Any},
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_owsmp_get_corridors(_api::OwsmpAuctionsApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_owsmp_get_corridors_OwsmpAuctionsApi, "/owsmp/getcorridors", ["OwsmpApiKey", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List corridors

Enumerate corridor identifiers usable for `getauctions`/`getcurtailment`.

Params:

Return: Vector{Any}, OpenAPI.Clients.ApiResponse
"""
function owsmp_get_corridors(_api::OwsmpAuctionsApi; _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_corridors(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function owsmp_get_corridors(_api::OwsmpAuctionsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_corridors(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_owsmp_get_curtailment_OwsmpAuctionsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Any},
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_owsmp_get_curtailment(_api::OwsmpAuctionsApi, corridor::String, fromdate::Date; todate=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_owsmp_get_curtailment_OwsmpAuctionsApi, "/owsmp/getcurtailment", ["OwsmpApiKey", ])
    OpenAPI.Clients.set_param(_ctx.query, "corridor", corridor; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "fromdate", fromdate; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "todate", todate; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Curtailment records for a corridor

Curtailment events on a corridor over a date range. Records carry `curtailmentPeriodStart`/`curtailmentPeriodStop`.

Params:
- corridor::String (required)
- fromdate::Date (required)
- todate::Date

Return: Vector{Any}, OpenAPI.Clients.ApiResponse
"""
function owsmp_get_curtailment(_api::OwsmpAuctionsApi, corridor::String, fromdate::Date; todate=nothing, _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_curtailment(_api, corridor, fromdate; todate=todate, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function owsmp_get_curtailment(_api::OwsmpAuctionsApi, response_stream::Channel, corridor::String, fromdate::Date; todate=nothing, _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_curtailment(_api, corridor, fromdate; todate=todate, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_owsmp_get_horizons_OwsmpAuctionsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Any},
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_owsmp_get_horizons(_api::OwsmpAuctionsApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_owsmp_get_horizons_OwsmpAuctionsApi, "/owsmp/gethorizons", ["OwsmpApiKey", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List auction horizons

Enumerate horizon values — `Yearly`, `Monthly`, `Weekly`, `Daily`, `Intraday`.

Params:

Return: Vector{Any}, OpenAPI.Clients.ApiResponse
"""
function owsmp_get_horizons(_api::OwsmpAuctionsApi; _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_horizons(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function owsmp_get_horizons(_api::OwsmpAuctionsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_owsmp_get_horizons(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export owsmp_get_auctions
export owsmp_get_bids
export owsmp_get_corridors
export owsmp_get_curtailment
export owsmp_get_horizons
