# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PublicationToolNordicDAApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PublicationToolNordicDAApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PublicationToolNordicDAApi }) = "https://publicationtool.jao.eu/core/api"

const _returntypes_publicationtool_nordic_da_cgm_forecast_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_cgm_forecast(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_cgm_forecast_PublicationToolNordicDAApi, "/publicationtool/nordic/data/cgmForeCast", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic CGM forecast (Nordic d2CF alias)

Common Grid Model forecast — Nordic naming for the Core-side `d2CF` endpoint.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_cgm_forecast(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_cgm_forecast(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_cgm_forecast(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_cgm_forecast(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_congestion_income_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_congestion_income(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_congestion_income_PublicationToolNordicDAApi, "/publicationtool/nordic/data/congestionIncome", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic congestion income per border

Nordic day-ahead congestion rent per border (EUR).

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_congestion_income(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_congestion_income(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_congestion_income(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_congestion_income(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_fb_domain_shadow_price_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_fb_domain_shadow_price(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_nordic_da_fb_domain_shadow_price", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_nordic_da_fb_domain_shadow_price", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_fb_domain_shadow_price_PublicationToolNordicDAApi, "/publicationtool/nordic/data/fbDomainShadowPrice", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic active-constraint shadow prices

Per-CNEC shadow prices for the binding Nordic active constraints (Shape A — paginated).

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_fb_domain_shadow_price(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_fb_domain_shadow_price(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_fb_domain_shadow_price(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_fb_domain_shadow_price(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_final_computation_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_final_computation(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_nordic_da_final_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_nordic_da_final_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_final_computation_PublicationToolNordicDAApi, "/publicationtool/nordic/data/finalComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Final Nordic FB domain (CNECs + PTDFs)

Final computation of the Nordic flow-based domain.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_final_computation(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_final_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_final_computation(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_final_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_initial_computation_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_initial_computation(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_nordic_da_initial_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_nordic_da_initial_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_initial_computation_PublicationToolNordicDAApi, "/publicationtool/nordic/data/initialComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Initial Nordic FB domain

Initial Nordic FB domain output prior to validation.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_initial_computation(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_initial_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_initial_computation(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_initial_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_max_exchanges_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_max_exchanges(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_max_exchanges_PublicationToolNordicDAApi, "/publicationtool/nordic/data/maxExchanges", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic max bilateral exchanges

Per-border max bilateral exchange limits in the Nordic CCR.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_max_exchanges(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_max_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_max_exchanges(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_max_exchanges(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_max_net_positions_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_max_net_positions(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_max_net_positions_PublicationToolNordicDAApi, "/publicationtool/nordic/data/maxNetPos", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic min/max net positions per zone

Per-zone min and max net-position bounds for Nordic zones.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_max_net_positions(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_max_net_positions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_max_net_positions(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_max_net_positions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_monitoring_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_monitoring(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_monitoring_PublicationToolNordicDAApi, "/publicationtool/nordic/system/monitoring", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic publication monitoring

Process monitoring records for the Nordic CCR — served from `/system/`.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_monitoring(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_monitoring(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_monitoring(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_monitoring(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_prefinal_computation_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_prefinal_computation(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_nordic_da_prefinal_computation", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_nordic_da_prefinal_computation", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_prefinal_computation_PublicationToolNordicDAApi, "/publicationtool/nordic/data/preFinalComputation", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Pre-final Nordic FB domain

Pre-final Nordic flow-based domain, before TSO validation reductions.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_prefinal_computation(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_prefinal_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_prefinal_computation(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_prefinal_computation(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_refprog_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_refprog(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_refprog_PublicationToolNordicDAApi, "/publicationtool/nordic/data/refprog", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic reference programs

Reference programs feeding the Nordic flow-based computation.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_refprog(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_refprog(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_refprog(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_refprog(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_spanning_default_fbp_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_spanning_default_fbp(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_spanning_default_fbp_PublicationToolNordicDAApi, "/publicationtool/nordic/data/spanningDefaultFBP", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic default-FBP status

Nordic default flow-based parameters fallback indicator.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_spanning_default_fbp(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_spanning_default_fbp(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_spanning_default_fbp(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_spanning_default_fbp(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_nordic_da_validation_reductions_PublicationToolNordicDAApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_nordic_da_validation_reductions(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_nordic_da_validation_reductions_PublicationToolNordicDAApi, "/publicationtool/nordic/data/validationReductions", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Nordic TSO validation reductions

Per-TSO Nordic validation reductions.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_nordic_da_validation_reductions(_api::PublicationToolNordicDAApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_validation_reductions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_nordic_da_validation_reductions(_api::PublicationToolNordicDAApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_nordic_da_validation_reductions(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export publicationtool_nordic_da_cgm_forecast
export publicationtool_nordic_da_congestion_income
export publicationtool_nordic_da_fb_domain_shadow_price
export publicationtool_nordic_da_final_computation
export publicationtool_nordic_da_initial_computation
export publicationtool_nordic_da_max_exchanges
export publicationtool_nordic_da_max_net_positions
export publicationtool_nordic_da_monitoring
export publicationtool_nordic_da_prefinal_computation
export publicationtool_nordic_da_refprog
export publicationtool_nordic_da_spanning_default_fbp
export publicationtool_nordic_da_validation_reductions
