# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PublicationToolItalyNorthApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PublicationToolItalyNorthApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PublicationToolItalyNorthApi }) = "https://publicationtool.jao.eu/core/api"

const _returntypes_publicationtool_italynorth_da_allocation_constraint_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_da_allocation_constraint(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_da_allocation_constraint_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_allocationConstraint", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North day-ahead allocation constraints

Allocation constraints applied to the Italy North day-ahead allocation.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_da_allocation_constraint(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_da_allocation_constraint(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_da_cnec_info_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_da_cnec_info(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_italynorth_da_cnec_info", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_italynorth_da_cnec_info", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_da_cnec_info_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_cnecInfo", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North day-ahead CNECs

Italy North day-ahead critical network elements and contingencies.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_da_cnec_info(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_cnec_info(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_da_cnec_info(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_cnec_info(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_da_final_ttc_ntc_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_da_final_ttc_ntc(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_da_final_ttc_ntc_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_FinalTtcNtc", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North day-ahead final TTC/NTC

Final TTC and NTC values published for the Italy North day-ahead window.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_da_final_ttc_ntc(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_final_ttc_ntc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_da_final_ttc_ntc(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_final_ttc_ntc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_da_forecasted_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_da_forecasted(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_da_forecasted_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_forecasted", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North day-ahead grid forecasts

Italy North forecasted grid status for the DA timeframe.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_da_forecasted(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_forecasted(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_da_forecasted(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_da_forecasted(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_id_allocation_constraint_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_id_allocation_constraint(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_id_allocation_constraint_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_idAllocationConstraint", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North intraday allocation constraints

Allocation constraints applied to the Italy North intraday allocation.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_id_allocation_constraint(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_id_allocation_constraint(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_allocation_constraint(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_id_cnec_info_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DomainEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_id_cnec_info(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("skip", "publicationtool_italynorth_id_cnec_info", :minimum, skip, 0, false)

    OpenAPI.validate_param("take", "publicationtool_italynorth_id_cnec_info", :minimum, take, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_id_cnec_info_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_idCnecInfo", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "Skip", skip; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Take", take; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North intraday CNECs

Italy North intraday CNECs (same shape as DA).

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)
- skip::Int64
- take::Int64
- filter::String

Return: DomainEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_id_cnec_info(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_cnec_info(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_id_cnec_info(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; skip=nothing, take=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_cnec_info(_api, from_utc, to_utc; skip=skip, take=take, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_id_final_ttc_ntc_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_id_final_ttc_ntc(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_id_final_ttc_ntc_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_idFinalTtcNtc", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North intraday final TTC/NTC

Final TTC and NTC values for the Italy North intraday window.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_id_final_ttc_ntc(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_final_ttc_ntc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_id_final_ttc_ntc(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_final_ttc_ntc(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_publicationtool_italynorth_id_forecasted_PublicationToolItalyNorthApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DataEnvelope,
    Regex("^" * replace("400", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("401", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("404", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("429", "x"=>".") * "\$") => ProblemDetails,
    Regex("^" * replace("500", "x"=>".") * "\$") => ProblemDetails,
)

function _oacinternal_publicationtool_italynorth_id_forecasted(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_publicationtool_italynorth_id_forecasted_PublicationToolItalyNorthApi, "/publicationtool/ibwt/data/CCR_idForecasted", ["PublicationToolBearer", ])
    OpenAPI.Clients.set_param(_ctx.query, "FromUtc", from_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_param(_ctx.query, "ToUtc", to_utc; style="form", is_explode=true)  # type ZonedDateTime
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", "application/problem+json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Italy North intraday grid forecasts

Italy North intraday-timeframe forecasted grid status.

Params:
- from_utc::ZonedDateTime (required)
- to_utc::ZonedDateTime (required)

Return: DataEnvelope, OpenAPI.Clients.ApiResponse
"""
function publicationtool_italynorth_id_forecasted(_api::PublicationToolItalyNorthApi, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_forecasted(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function publicationtool_italynorth_id_forecasted(_api::PublicationToolItalyNorthApi, response_stream::Channel, from_utc::ZonedDateTime, to_utc::ZonedDateTime; _mediaType=nothing)
    _ctx = _oacinternal_publicationtool_italynorth_id_forecasted(_api, from_utc, to_utc; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export publicationtool_italynorth_da_allocation_constraint
export publicationtool_italynorth_da_cnec_info
export publicationtool_italynorth_da_final_ttc_ntc
export publicationtool_italynorth_da_forecasted
export publicationtool_italynorth_id_allocation_constraint
export publicationtool_italynorth_id_cnec_info
export publicationtool_italynorth_id_final_ttc_ntc
export publicationtool_italynorth_id_forecasted
