# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module JAOEUAPI

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "0.1.0"

include("modelincludes.jl")

include("apis/api_OwsmpAuctionsApi.jl")
include("apis/api_PublicationToolCoreDAApi.jl")

# export models
export DataEnvelope
export DomainEnvelope
export ProblemDetails

# export operations
export OwsmpAuctionsApi
export PublicationToolCoreDAApi

end # module JAOEUAPI
