# JAO routes one logical API onto two physically distinct hosts: the
# Publication Tool (anonymous bearer, JSON, paginated/range envelopes) and
# OWSMP (`AUTH_API_KEY` header, bare-array JSON). The OpenAPI spec keeps
# them in a single file under synthetic path prefixes (`/publicationtool/...`,
# `/owsmp/...`) so codegen produces one Julia function per logical query.
# The routing hook below strips that prefix at request time and the
# per-platform constructors point the inner client at the right host.

using OpenAPI: OpenAPI

using .JAOEUAPI: PublicationToolCoreDAApi, OwsmpAuctionsApi

const PUBLICATIONTOOL_CORE_BASE = "https://publicationtool.jao.eu/core/api"
const OWSMP_BASE = "https://api.jao.eu/OWSMP"

# Synthetic-path prefixes generated by `scripts/build_openapi.jl`. The
# `OpenAPI.Clients.Ctx` constructor concatenates `client.root` and the
# operation's resource path, so by the time our pre_request_hook fires
# the synthetic prefix is embedded mid-URL, not at position 1. We strip
# it via single replace on the full URL.
const _SYNTHETIC_PREFIXES = ("/publicationtool/core", "/owsmp")

"""
    _strip_synthetic_prefix(url) -> String

Remove the JAO-synthetic-tag prefix from `url` so the URL that hits the
wire matches the real upstream layout. The synthetic prefixes only
disambiguate one OpenAPI operation from another in the spec; the actual
JAO servers know nothing about them. Operates on the *full URL* produced
by `OpenAPI.Clients.Ctx` (host + base path + synthetic prefix + endpoint).
"""
function _strip_synthetic_prefix(url::AbstractString)
    for prefix in _SYNTHETIC_PREFIXES
        idx = findfirst(prefix, url)
        idx === nothing && continue
        return string(
            SubString(url, 1, first(idx) - 1),
            SubString(url, last(idx) + 1)
        )
    end
    return String(url)
end

# Two-stage pre_request_hook: stage 1 is a pass-through (Ctx is immutable,
# so we can't rewrite the resource there), stage 2 applies the
# platform-specific Auth and rewrites the assembled URL.
function _routing_hook(auth::Auth)
    hook(ctx) = ctx
    function hook(resource::AbstractString, body, headers::Dict{String, String})
        apply!(auth, headers)
        return _strip_synthetic_prefix(resource), body, headers
    end
    return hook
end

"""
    PublicationToolClient(; bearer = nothing) -> Client

Build a [`Client`](@ref) for the Publication Tool's Core day-ahead
flow-based market coupling data. The portal embeds an anonymous Guest
bearer in its SPA bundle; the API is effectively public, so `bearer`
defaults to `nothing` (no `Authorization` header sent). Pass a token
explicitly only if JAO has issued you one with elevated role.
"""
function PublicationToolClient(; bearer::Union{Nothing, AbstractString} = nothing)
    auth = bearer === nothing ? NoAuth() : BearerToken(String(bearer))
    inner = OpenAPI.Clients.Client(
        PUBLICATIONTOOL_CORE_BASE;
        pre_request_hook = _routing_hook(auth),
    )
    return Client(inner, auth, PUBLICATIONTOOL_CORE_BASE)
end

"""
    OwsmpClient(api_key) -> Client

Build a [`Client`](@ref) for the OWSMP cross-border capacity auctions
API. `api_key` is sent on every request as the `AUTH_API_KEY` header.
Tokens are issued by JAO's helpdesk on request (email `helpdesk@jao.eu`
with subject `[API] Token Request` after accepting the T&Cs).
"""
function OwsmpClient(api_key::AbstractString)
    auth = APIKey(String(api_key); header = "AUTH_API_KEY")
    inner = OpenAPI.Clients.Client(
        OWSMP_BASE;
        pre_request_hook = _routing_hook(auth),
    )
    return Client(inner, auth, OWSMP_BASE)
end

"""
    publicationtool_core_da_api(client) -> PublicationToolCoreDAApi

Build the generated low-level API binding for the Publication Tool's
Core day-ahead surface. Pass to any `publicationtool_core_da_*`
function (defined in [`JAOEU.JAOEUAPI`](@ref)).
"""
publicationtool_core_da_api(client::Client) =
    PublicationToolCoreDAApi(client.inner)

"""
    owsmp_auctions_api(client) -> OwsmpAuctionsApi

Build the generated low-level API binding for the OWSMP auctions
surface. Pass to any `owsmp_*` function (defined in [`JAOEU.JAOEUAPI`](@ref)).
"""
owsmp_auctions_api(client::Client) = OwsmpAuctionsApi(client.inner)
