# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DataEnvelope

    DataEnvelope(;
        data=nothing,
    )

    - data::Vector{Any} : Records for the requested time window. Each row carries &#x60;dateTimeUtc&#x60; plus endpoint-specific fields (e.g. &#x60;hub_&lt;ZONE&gt;&#x60; for net positions, &#x60;border_&lt;FROM&gt;_&lt;TO&gt;&#x60; for exchange-shaped data).
"""
Base.@kwdef mutable struct DataEnvelope <: OpenAPI.APIModel
    data::Union{Nothing, Vector{Any}} = nothing

    function DataEnvelope(data, )
        o = new(data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DataEnvelope

const _property_types_DataEnvelope = Dict{Symbol,String}(Symbol("data")=>"Vector{Any}", )
OpenAPI.property_type(::Type{ DataEnvelope }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DataEnvelope[name]))}

function OpenAPI.check_required(o::DataEnvelope)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DataEnvelope)
    OpenAPI.validate_property(DataEnvelope, Symbol("data"), o.data)
end

function OpenAPI.validate_property(::Type{ DataEnvelope }, name::Symbol, val)

end
