# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DomainEnvelope

    DomainEnvelope(;
        totalRowsWithFilter=nothing,
        data=nothing,
    )

    - totalRowsWithFilter::Int64 : Total rows matching the filter, ignoring pagination. Issue the first call with &#x60;Take&#x3D;0&#x60; to read this without transferring data.
    - data::Vector{Any} : Records for the requested page. Shape depends on the endpoint; CNEC records include &#x60;dateTimeUtc&#x60;, &#x60;cnecName&#x60;, &#x60;contingencies[]&#x60;, and a set of &#x60;ptdf_&lt;HUB&gt;&#x60; columns.
"""
Base.@kwdef mutable struct DomainEnvelope <: OpenAPI.APIModel
    totalRowsWithFilter::Union{Nothing, Int64} = nothing
    data::Union{Nothing, Vector{Any}} = nothing

    function DomainEnvelope(totalRowsWithFilter, data, )
        o = new(totalRowsWithFilter, data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DomainEnvelope

const _property_types_DomainEnvelope = Dict{Symbol,String}(Symbol("totalRowsWithFilter")=>"Int64", Symbol("data")=>"Vector{Any}", )
OpenAPI.property_type(::Type{ DomainEnvelope }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DomainEnvelope[name]))}

function OpenAPI.check_required(o::DomainEnvelope)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DomainEnvelope)
    OpenAPI.validate_property(DomainEnvelope, Symbol("totalRowsWithFilter"), o.totalRowsWithFilter)
    OpenAPI.validate_property(DomainEnvelope, Symbol("data"), o.data)
end

function OpenAPI.validate_property(::Type{ DomainEnvelope }, name::Symbol, val)


end
