# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProblemDetails
RFC 7807 problem detail returned on 4xx/5xx by the Publication Tool&#39;s ASP.NET Core middleware.

    ProblemDetails(;
        type=nothing,
        title=nothing,
        status=nothing,
        detail=nothing,
        instance=nothing,
        errors=nothing,
    )

    - type::String
    - title::String
    - status::Int64
    - detail::String
    - instance::String
    - errors::Dict{String, Vector{String}}
"""
Base.@kwdef mutable struct ProblemDetails <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    title::Union{Nothing, String} = nothing
    status::Union{Nothing, Int64} = nothing
    detail::Union{Nothing, String} = nothing
    instance::Union{Nothing, String} = nothing
    errors::Union{Nothing, Dict{String, Vector{String}}} = nothing

    function ProblemDetails(type, title, status, detail, instance, errors, )
        o = new(type, title, status, detail, instance, errors, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ProblemDetails

const _property_types_ProblemDetails = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("title")=>"String", Symbol("status")=>"Int64", Symbol("detail")=>"String", Symbol("instance")=>"String", Symbol("errors")=>"Dict{String, Vector{String}}", )
OpenAPI.property_type(::Type{ ProblemDetails }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProblemDetails[name]))}

function OpenAPI.check_required(o::ProblemDetails)
    true
end

function OpenAPI.validate_properties(o::ProblemDetails)
    OpenAPI.validate_property(ProblemDetails, Symbol("type"), o.type)
    OpenAPI.validate_property(ProblemDetails, Symbol("title"), o.title)
    OpenAPI.validate_property(ProblemDetails, Symbol("status"), o.status)
    OpenAPI.validate_property(ProblemDetails, Symbol("detail"), o.detail)
    OpenAPI.validate_property(ProblemDetails, Symbol("instance"), o.instance)
    OpenAPI.validate_property(ProblemDetails, Symbol("errors"), o.errors)
end

function OpenAPI.validate_property(::Type{ ProblemDetails }, name::Symbol, val)






end
